// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irawubibldjrnfawfssw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyYXd1YmlibGRqcm5mYXdmc3N3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NzA2NDksImV4cCI6MjA2MjM0NjY0OX0.pNF1Zq_kVyS3o2b7tmLqBgscgk3eitiJpwkNVjfvOPA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);